### ISSUE TITLE
"Folding"の訳について

### ISSUE THREAD

**Issue by kn1cht** [kn1cht/Translate#5]
### 目的
`home.yaml` を読んでいて、foldingの訳に一貫したルールが必要だと感じたので議論したいです。
そんなに厳格に決めなくてもいいのかもしれませんが、本プロジェクトで最重要級かつ頻出の単語なので、日本人の読者の誤読を招かないよう慎重に訳したいと考えています。

### 問題の整理
foldingという単語は、Folding@homeのサイトでは主に2つの意味で使われています。

1. 生物学用語としての、タンパク質の折りたたみ
    - e.g. `Folding refers to the way human protein folds in the cells that make up your body.`
2. Folding@homeが実施しているプロジェクトそのもの、またはその参加者が計算を回すこと
    - e.g. `Start folding now!`

翻訳プロジェクトでもこの意味の違いは認識されていて、メインリポジトリのWikiに以下の記載がありました。

https://github.com/FoldingCommunity/Translate/wiki#language-style
> The term "Folding" should be translated as the correct scientific term in each language for serious descriptions. However, in some case it might be necessary to alter its translation depending on context, e.g. "Some of us are quite intense in our approach to folding." in https://foldingathome.org/statistics/

従って、①foldingが生物学の文脈で使われている場合と、②F@hの文脈で使われている場合を個別に判断して訳す必要があります。

### 提案
①の生物学用語のほうは「折りたたみ」と訳すのが日本語では一般的なようです（[念のため論文検索しました](https://scholar.google.com/scholar?hl=ja&as_sdt=0%2C5&q=%E6%8A%98%E3%82%8A%E3%81%9F%E3%81%9F%E3%81%BF%E3%80%80%E3%82%BF%E3%83%B3%E3%83%91%E3%82%AF%E8%B3%AA&btnG=)）し、訳に悩むこともないでしょう。

問題は②の方です。ありそうな選択肢としては

- ①と特に区別しないで「**折りたたみ**」と訳す
    - > e.g. Start folding now! → 今すぐ折りたたみを始めよう！
    - pros
        - 原文でも両方foldingだし、読み手に文脈で判断してもらうことはできそう
    - cons
        - 日本人の読者が「folding = 折りたたみ」だと事前に知っているとは限らない。知らない人にとっては意味不明な文章になる
- 「**フォールディング**」と訳す
    - > e.g. Start folding now! → 今すぐフォールディングを始めよう！
    - pros
        - 読みそのままなので、英単語が読める人なら「フォールディングはfoldingのことだな」と気づいてもらえそう
    - cons
        - やはり文字が変わっているので「フォールディング=Folding@home」と結びつかない読者がいるかも？
- 「**Folding@home**」と訳す
    - > e.g. Start folding now! → 今すぐFolding@homeを始めよう！
    - pros
        - 省略せずにいちいちFolding@homeと書くのが最も明確に意味が伝わると考えられる
    - cons
        - Folding@homeだらけになって文章がごちゃごちゃしないか？
        - 他言語版の対応とはおそらく食い違う（私が見た範囲では、foldingは各言語での「折りたたみ」を表す単語になっていました）

**Comment by kn1cht** [comment]
（自分の意見を書いていなかった 😅 ）
私は最後の「Folding@homeと訳す」が明確でいいかなぁと思っていましたが、 @shino-zxc さんの訳を読んでいて「フォールディングと訳す」の方が良さそうだと思うようになりました。
カタカナが使える日本語の利点を活かして、「生物学用語は『折りたたみ』、F@h自体のことなら『フォールディング』」と区別すれば、読者が文脈で判断する必要なく、明確な文章になるのではないでしょうか。

https://github.com/FoldingCommunity/Translate/pull/65

**Comment by mitz-ext** [comment]
個人的には「フォールディング」の第一印象が未知の用語という感じを受けました。初見だからかな...
カッコ付きの『折りたたみ』にして、初出時のみ『折りたたみ(=Folding)』のような書き方にするのはいかがでしょうか。

**Comment by kn1cht** [comment]
> 個人的には「フォールディング」の第一印象が未知の用語という感じを受けました。初見だからかな...

確かに「分かりにくいな」と感じさせてしまうのは良くないですね。

> カッコ付きの『折りたたみ』にして、初出時のみ『折りたたみ(=Folding)』のような書き方にするのはいかがでしょうか。

区別という観点ではよさそうに思います。ただ、例えばトップページ（home.yaml）冒頭の「START FOLDING NOW」のような短い部分にまで使うと「いますぐ『折りたたみ』を始めましょう」という感じになって、これはこれで「『折りたたみ』ってなんだろう？」と疑問を持たれてしまいそうです。
https://foldingathome.org/

やはり、home.yaml冒頭の場合は「いますぐFolding@homeを始めましょう」「既にFolding@homeに参加している方」のように省略せず書くほうがよいでしょうかね？

**Comment by shino-zxc** [comment]
ホームページや文献を読んでいると①はさらに①－1「タンパク質が折りたたまれる現象の名前」と①－2「折りたたまれる過程」がどっちもfold(ing)で使われている気がします。
「タンパク質が折りたたまれる現象の名前」を「タンパク質フォールディング」、「折りたたまれる過程」は「折りたたみ」としている文献も多いので、変に和訳せずカタカナにして生物現象名としての「folding」も「タンパク質フォールディング」や「フォールディング」の方が専門用語（＝未知の用語）であることが明確になって分かりやすい気がしていますが、どうでしょうか。。。
misfoldingはミスフォールディングと訳すほかなさそうなので、そことの対応も取りやすい気がします。

個人的にこんなイメージでいます。
「折りたたまれる現象の名前」としてのfoldingは「タンパク質フォールディング」
「折りたたまれる過程」としてのfoldingは「折りたたみ」
「Folding@home」の愛称としてのfoldingは「フォールディング」

mitz-extさんのおっしゃるようにとっつきやすさを優先して冒頭は併記・明記しつつ、ごちゃごちゃしないように統一していく感じがよい気がします。

**Comment by kn1cht** [comment]
> 「タンパク質が折りたたまれる現象の名前」を「タンパク質フォールディング」、「折りたたまれる過程」は「折りたたみ」としている文献も多い

なるほど、参考になりました。文献での慣習があるなら合わせた方が良さそうですね。

> misfoldingはミスフォールディングと訳すほかなさそうなので

PR #6 へのコメントにも書いたのですが、「異常な折りたたみ」「折りたたみ異常」はありうるかなと思っていました。あまり使われていない表現ですかね？

- （例）[がんの有害なタンパク質折りたたみ異常 | Nature Chemical Biology | Nature Research](https://www.natureasia.com/ja-jp/nchembio/pr-highlights/1168)
- 「異常折りたたみ」という用語を使っている科研費の報告書 https://kaken.nii.ac.jp/ja/file/KAKENHI-PROJECT-16K15317/16K15317seika.pdf

**Comment by shino-zxc** [comment]
フォールディング異常、折り畳みの誤り、正しい立体構造が形成されない等々見かけましたが、まわりくどい印象はうけます。
「折りたたみ異常」が一番シンプルな気がするので、「折りたたみ」「折りたたみ異常」統一するのがよいでしょうか。。。
J-stageで調べると「フォールディング」「ミスフォールディング」を使った文献が多いのが悩みどころです。

> 「折りたたまれる過程」は「折りたたみ」としている文献も多い

読み返すと語弊がありました。
タンパク質フォールディング（名詞）はタンパク質が特定の立体構造に折りたたまれる（動詞）みたいな使い方が多い印象を持っています。（生物屋ではないので、文献調べた限りの印象です。）

**Comment by kn1cht** [comment]
> 「折りたたみ異常」が一番シンプルな気がするので、「折りたたみ」「折りたたみ異常」統一するのがよいでしょうか。。。

私はこれに一票です。
F@hのホームページは論文ではなく一般向けの文章なので、「なんか専門用語がいっぱい出てきて難しいな」と思われる書き方は避けたいです。
従って、不正確にならない範囲内で書き方に自由度があるならば、「折りたたみ」「折りたたみ異常」「折りたたまれる」と一貫した表現を維持するのがいいと考えています。

（話が広がってきたので一応書きますが、これは①生物学用語の"folding"の話です。②の方はまた別ですね）

**Comment by Le96** [comment]
> 「折りたたみ異常」が一番シンプルな気がするので、「折りたたみ」「折りたたみ異常」統一するのがよいでしょうか。。。

同じく私もこちらに一票です。日本語的に見た目で理解しやすい方が一般の方にはとっつきやすい印象を受けますね。
（これは①生物学用語のfoldingについてですね）
②の計算としては、あくまで意見になるのですが『折りたたみ計算』なども一般の日本語話者に対して伝わりやすいのかな、と考えています。

**Comment by kn1cht** [comment]
@Le96 ありがとうございます。折りたたみ計算もいいですね。

皆さんのイメージが湧きやすいように、トップページに今出ている案を仮置きしてみました。

a. 計算の文脈でのfolding → フォールディング
![1](https://user-images.githubusercontent.com/16277200/85742024-df920c00-b73d-11ea-9f7a-15095019385e.PNG)

b. 計算の文脈でのfolding → Folding@home
（追記）あ、上段オレンジボタンの上の文章が折りたたみ計算のままになってました……
![2](https://user-images.githubusercontent.com/16277200/85742031-e0c33900-b73d-11ea-8e96-b15e8ab23691.PNG)

c. 計算の文脈でのfolding → 折りたたみ計算
![3](https://user-images.githubusercontent.com/16277200/85742038-e1f46600-b73d-11ea-8466-911ad8f6e9ce.PNG)

**Comment by shino-zxc** [comment]
@kn1cht イメージ画像ありがとうございます。
ｃ案は”計算”が少し難しい印象を与えそうなので、a案かｂ案が良いかなと思いました。

ただ、最初の提案のようにa案だと用語を知らないと”フォールディング”って何？という印象を持たれそうです。
